name: Deploy Backend to AWS

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Install Serverless Framework
      run: npm install -g serverless@3
    
    - name: Deploy to AWS Lambda
      working-directory: ./backend
      run: |
        serverless deploy --stage dev --verbose
    
    - name: Get API Endpoint
      if: success()
      run: |
        API_URL=$(serverless info --stage dev --verbose | grep -oP 'https://[^\s]+' | head -1)
        echo "✅ Backend deployed successfully"
        echo "🔗 API Endpoint: $API_URL"
        echo "::set-output name=api_url::$API_URL"

